# Generated by Django 5.1.7 on 2025-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Ethics', 'Ethics'), ('Logic', 'Logic'), ('Metaphysics', 'Metaphysics'), ('Epistemology', 'Epistemology'), ('Aesthetics', 'Aesthetics'), ('Existentialism', 'Existentialism'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
